### ISSUE TITLE
Please update webui to webui2 interface

### ISSUE THREAD

**Issue by jangeador** [rohit01/docker_shinken#17]
The webui2 interface is much nicer than webui and it has plenty of features which could help us.

**Comment by jangeador** [comment]
@rohit01 I can work on this. I will try to make it an optional addition to the current webui. Thanks for making me a collaborator to this project.

**Comment by jangeador** [comment]
@rohit01 I am able to replace webui with webui2 however I cannot make them run at the same time. Would you like to replace webui with webui2?

It looks really awesome!

![image](https://cloud.githubusercontent.com/assets/429042/18887996/6f6661ba-84ab-11e6-8b81-e6a1d559cd09.png)

**Comment by rohit01** [comment]
@jangeador Yes, WebUi2 is better. We can replace the existing one.

**Comment by jangeador** [comment]
addressed in #18
