### ISSUE TITLE
Error 404: Not Found on /wall

### ISSUE THREAD

**Issue by ivancasco** [rohit01/docker_shinken#2]
Hi,

I get Not found: '/wall' when i try to access the webui wall. I'm using basic shinken.

Thanks a lot.

**Comment by kisimere** [comment]
It seems that the newest shinken release does not work with the webui. Changing to the 2.0 release seems to fix that
https://github.com/kisimere/docker_shinken/commit/83d2b89e97bb05be7d65ec66172362cdf6483018

**Comment by rohit01** [comment]
Fixed: https://github.com/rohit01/docker_shinken/pull/3
Courtesy: @kisimere 

Docker tag for shinken 2.0 is also created.
