### ISSUE TITLE
not  able to login as admin/admin

### ISSUE THREAD

**Issue by phulei** [rohit01/docker_shinken#7]
Hi Rohit,

I used the default login seems like not able to login to shinken UI
 the htpasswd.user is as below
## Apache/Nginx htpasswd file for Basic Authentication
# 
# The passwords can be managed in this file using the apache utililty: htpasswd
# Installation:
# sudo apt-get install apache2-utils
# Use:
# htpasswd -c htpasswd.users <username>
# Default:
# Username: admin
# Password: admin
# 

admin:$apr1$xvoEHgxj$QZ5pR9Y565MagnqJy3ZJx1
~  
Thanks
phulei

**Comment by rohit01** [comment]
Did you mount the custom_configs/ folder in your docker? Was the path correct?  
The login credential file in in custom_configs/ directory.

**Comment by rohit01** [comment]
Hope it solved the issue. Closing this. Feel free to re-open.
